
POST http://localhost:8283/gringotts/vaults/authenticate HTTP/1.1
content-type: application/json

{
    "vault_owner": "hpotter",
    "vault_number": "713",
    "vault_key": "griffindoor"

}


###

GET http://localhost:8283/gringotts/vaults/appraisal?vault_id=713
Authorization: Bearer token_here
